eureka:
  client:
    service-url:
      # 将服务注册到 Eureka Serve 上
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          # 存放配置文件的 git 地址
          uri: https://github.com/wqlm/myTest
          # 存放 git 仓库的本地地址
          basedir: D:\Desktop\wqlm\Spring Cloud\config_git